### ISSUE TITLE
Python3 Jupyter notebook loading issue :- load %reload_ext sql_magic 

### ISSUE THREAD

**Issue by blackhat06** [pivotal-legacy/sql_magic#10]
I am getting a syntax error while loading this:

%reload_ext sql_magic 

File "/usr/local/lib/python3.7/site-packages/sql_magic/sql_magic.py", line 28, in <module>
    from .connection import Connection

  File "/usr/local/lib/python3.7/site-packages/sql_magic/connection.py", line 106
    table_name, show_output, notify_result, force_caller, async = [options[k] for k in option_keys]
                                                              ^
SyntaxError: invalid syntax

**Comment by dpipkin** [comment]
If you downgrade to python 3.6 it should work again.

That's just a stopgap, though. `async` is a reserved keyword in Python 3.7 so that variable will have to be renamed.

**Comment by scottcode** [comment]
Thanks to @dpipkin's pull request, this issue should now be resolved. @blackhat06, let me know if it's still a problem and I can reopen the issue.

**Comment by tkang007** [comment]
I will very appreciate if anyone release resolved code at PYPI repo for pip easier installation.
I can user pip from this repo, but it make difficulty for others
Thanks.

**Comment by crawles** [comment]
it's updated now

**Comment by tkang007** [comment]
Thanks so much. Really appreciate your contributions. - Taewon

**Comment by crawles** [comment]
No problem, glad you find the package useful!
